### ISSUE TITLE
🚀 Feature: Provide auto-fixing

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/sentences-per-line#24]
https://github.com/DavidAnson/markdownlint/issues/80

This seems like a trivial feature to add: replace a complaining `". "` with `".\n "`.

Knowing whether to use `\r\n` or `\n` is a harder problem. I'm ok with not tackling it 😉.

**Comment by DavidAnson** [comment]
@JoshuaKGoldberg Good news, `\n` is platform-independent in a custom rule fix! More info here: https://github.com/DavidAnson/markdownlint/blob/main/doc/CustomRules.md

**Comment by JoshuaKGoldberg** [comment]
On second thought, removing `good first issue`. Still accepting PRs though - I just think this is best done by someone who's a little more familiar with the codebase than an absolute beginner.
